User Agent: 'Taskerbot run by /u/davidm5375'
Username: 'MySocksAreSoggy'
Password: 'SoggySocks'
Client ID: 'gZmSEhXZbHP_sw'
Client Secret: '9Lm_1QhCmanuCjkt24pXZZ4qiJo'
Subreddits:
    - 'WebsiteForum'
